### PR TITLE
RetryBackOff param for FailJobCommand

### PR DESCRIPTION
**Pull request by Ileksa**
In order to set backoff timeout parameter existing in grpc request I added retryBackOff parameter to FailJobCommand.

### CODE REVIEW

**Review by Zelldon — CHANGES_REQUESTED** [review]
Sorry for the delay! I was a while OOO.

Thanks for the contribution! Could you also add a test for it, please.

Furthermore, for the next time please have a look at the [contribution guideline]( https://github.com/camunda-community-hub/zeebe-client-csharp/blob/main/CONTRIBUTING.md) regarding git commit message guidelines.

**Comment by aanodin** [comment]
👍 
also interested in this one to be merged

**Comment by aanodin** [comment]
created #482 with tests

**Comment by Zelldon** [comment]
replaced by #482 thanks @aanodin

**Pull request closed without merging**
