### PR TITLE
Enhancement: OAuth2TokenProvider for Authentication Against Self-Hosted Camunda Stack (503)

### PR DESCRIPTION
**Pull request by LennartKleymann**
Hey! 👋 I've just introduced an OAuth2TokenProvider to facilitate authentication against a self-hosted zeebe stack. I'd love to hear your thoughts and feedback on this addition.

Changelog:

**OAuth2TokenProvider:**
- Introduced OAuth2TokenProvider for seamless authentication.
- Implemented OAuth2TokenProviderBuilder for flexibility in configuration.
- Moved AccessToken to the Misc Namespace and Folder for better organization.
- Extracted duplicated code from OAuth2TokenProvider and CamundaCloudTokenProvider into a common base class for improved maintainability.

**Integration Tests:**
- Enabled the initiation of integration tests with an identity zeebe stack.
- Added integration test to authenticate against the identity zeebe stack

**Unit Tests:**
- Implemented thorough unit tests for both OAuth2TokenProvider and OAuth2TokenProviderBuilder to ensure robust functionality.

Looking forward to your valuable feedback!

### CODE REVIEW

**Comment by Zelldon** [comment]
I try to review asap but zeebe project and other thing keep me busy :)

@fabianschurz maybe you want to give feedback from the user perspective if this would be something you would like to see and use like it is rjght now already.

**Comment by fabianschurz** [comment]
I reviewed the code, i don't have any improvements or additions. LGTM, it's implemented the same way the cloud provider is implemented at the moment. So for me this PR would be suitable and would exactly fit for my use case.

**Comment by FJuette** [comment]
I would love to see this PR accepted. After upgrading my local camunda-stack it was a nightmare to get authentication done right (before I made unauthorized requests). Thanks to this PR I have a workaround for token retrieval.

**Comment by Zelldon** [comment]
Hey, thanks all for your interest in this PR and especially to @LennartKleymann for contributing. I reiterated over it and created https://github.com/camunda-community-hub/zeebe-client-csharp/pull/625 (which is merged now). I will release a new version soon.

**Pull request closed without merging**
