### PR TITLE
#669 externalise dependency

### LINKED ISSUE #669: I can use the client with less dependencies
**Is your feature request related to a problem? Please describe.**
I want to reduce the amount of dependencies my projects have

**Describe the solution you'd like**
System.Threading.Tasks.Dataflow is removed as a dependency when the framework can provide it

**Describe alternatives you've considered**
Accept the dependencies 

**Additional context**
N/a

### PR DESCRIPTION
**Pull request by thompson-tomo**
closes #669

### CODE REVIEW

**Review by Zelldon — APPROVED** [review]
Thank you for your time and contribution 🙇🏼

**Review by Zelldon — CHANGES_REQUESTED** [review]
Please take a look at our contribution guide, we have some guidelines for the commit messages https://github.com/camunda/zeebe/blob/main/CONTRIBUTING.md#commit-message-guidelines 

Please adjust your commit header to something like`build: remove dataflow dependency` 

And please add some more description to why this change was necessary, so it is also clear for the afterworld

**Comment by thompson-tomo** [comment]
@Zelldon commit message has been updated as requested.

**Review by Zelldon — APPROVED** [review]
Thanks 👍🏼

**Pull request merged**
